$scrPath = $HOME/.local/share/bin

monitor = HDMI-A-1, 1440x900@59.887, 0x0, 1

exec-once = waybar
exec-once = swaybg -i /home/vishal/Pictures/wallpaper.png -m fill
exec-once = dunst

env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = QT_QPA_PLATFORM,wayland;xcb
env = MOZ_ENABLE_WAYLAND,1

input {
    kb_layout = us
    follow_mouse = 1
    sensitivity = 0
    accel_profile = adaptive
    numlock_by_default = true

    touchpad {
        natural_scroll = no
    }
}

dwindle {
    preserve_split = yes
}

master {
    new_status = master
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    force_default_wallpaper = 0
}

source = ~/.config/hypr/keybindings.conf
source = ~/.config/hypr/animations.conf
