windowrule = opacity 0.90 0.90, class:^(firefox)$
windowrule = opacity 0.90 0.90, class:^(Google-chrome)$
windowrule = opacity 0.90 0.90, class:^(Brave-browser)$
windowrule = opacity 0.80 0.80, class:^(code-oss)$
windowrule = opacity 0.80 0.80, class:^(kitty)$
windowrule = opacity 0.80 0.80, class:^(org.kde.dolphin)$
windowrule = opacity 0.80 0.80, class:^(vesktop)$
windowrule = opacity 0.80 0.80, class:^(discord)$
windowrule = opacity 0.70 0.70, class:^([Ss]team)$
windowrule = opacity 0.70 0.70, class:^([Ss]potify)$

windowrule = float, class:^(org.pulseaudio.pavucontrol)$
windowrule = float, class:^(blueman-manager)$
windowrule = float, class:^(nm-connection-editor)$
windowrule = float, class:^(kitty)$, title:^(btop)$

layerrule = blur, rofi
layerrule = ignorezero, rofi
layerrule = blur, swaync-notification-window
layerrule = ignorezero, swaync-notification-window
layerrule = blur, swaync-control-center
layerrule = ignorezero, swaync-control-center
layerrule = blur, logout_dialog
