general {
    col.active_border = rgba(313244ee) rgba(45475aee)
    col.inactive_border = rgba(313244aa) rgba(2a2b35aa)
}

decoration {
    rounding = 10

    blur {
        enabled = true
        size = 6
        passes = 3
        noise = 0.02
        contrast = 1
        brightness = 0.9
        vibrancy = 0.2
        vibrancy_darkness = 0.5
    }

    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1a55)
    }
}
